#ifndef HALIDE_FUSE_GPU_THREAD_LOOPS_H
#define HALIDE_FUSE_GPU_THREAD_LOOPS_H

/** \file
 * Defines the lowering pass that fuses and normalizes loops over gpu
 * threads to target CUDA, OpenCL, and Metal.
 */

#include <map>
#include <string>

#include "Expr.h"

namespace Halide {
namespace Internal {

class Function;

class Function;

/** Rewrite all GPU loops to have a min of zero. */
Stmt zero_gpu_loop_mins(const Stmt &s);

/** Prepare GPU warp-specialized async producers (async() +
 * store_in(GPUShared)) for thread-loop fusion. For each such producer, the
 * producer and consumer work is placed on disjoint warp groups by injecting an
 * extra outer GPU-thread dimension: the producer runs on group 0, the consumer
 * on group 1. The subsequent fuse_gpu_thread_loops pass then turns this into a
 * single launch where some warps produce (e.g. stage into shared memory) while
 * others consume. Runs after canonicalize_gpu_vars and select_gpu_api, before
 * fuse_gpu_thread_loops. Producers whose structure isn't yet supported are left
 * unchanged (they fall back to synchronous shared-memory staging). */
Stmt inject_gpu_warp_specialization(Stmt s, const std::map<std::string, Function> &env);

/** Lower device async Forks from warp-specialized ring producers (async() +
 * store_in(GPUShared) + ring_buffer()) into a warp-group split coordinated by
 * per-slot named barriers: producer warps stage into a shared ring while consumer
 * warps compute, running ahead by the ring depth. Runs after canonicalize_gpu_vars,
 * before inject_gpu_warp_specialization (which handles the non-ring case). */
Stmt lower_gpu_warp_async(Stmt s, const std::map<std::string, Function> &env, const Target &t);

/** Recognize a block-scope tile copy (a vectorized global->shared staging fill,
 * store_in(GPUShared)) and rewrite it to a TMA bulk-tensor load (sm_90). The cooperative
 * per-thread fill `produce As { for m,k { As[..] = A[..] } }` becomes one
 * cp.async.bulk.tensor (tma_load_2d) completed by an mbarrier: a block-level mbarrier_init,
 * a single-elected-thread arm (async_issue(CpAsyncBulk,bytes)) + tma_load_2d, and an
 * all-threads async_wait(CpAsyncBulk). The host CUtensorMap descriptor is built once per
 * launch by a `halide_cuda_tensor_map(src.buffer, box0, box1, swizzle)` let wrapping the
 * gpu_block (closure -> kernel arg). Single-thread issue is a codegen property of the TMA
 * intrinsics; the produce->consume + init->use barriers are GENERATED by InjectThreadBarriers
 * (tma_load's shared dst registers as a store), so no sync is hand-placed. Gated HL_WG_TMA +
 * sm_90; runs after lower_warp_group_tiles, before lower_async_completions (which lowers the
 * async_issue/async_wait markers it emits). See research/exec_mapping_model.md,
 * fusegpu_rearch_plan.md C.3/C.4a/M4. */
Stmt inject_tma_copies(Stmt s, const Target &t);

/** Lower async-completion requirements (Call::async_issue / async_wait, CompletionKind x
 * SyncScope x target) to their concrete mechanism. The CpAsyncBulk (sm_90 cp.async.bulk / TMA)
 * path becomes an mbarrier transaction: async_issue -> mbarrier_arrive_expect_tx, async_wait ->
 * mbarrier.try_wait.parity. Runs BEFORE fuse_gpu_thread_loops so the mbarrier init (materialized
 * as a shared store by the emitting recognizer) is seen by InjectThreadBarriers, which GENERATES
 * the transitive init->use visibility barrier (no hand-placed barrier; the F3 deadlock class
 * dissolves). See research/fusegpu_rearch_plan.md C.1a. */
Stmt lower_async_completions(Stmt s, const Target &t);

/** Converts Halide's GPGPU IR to the OpenCL/CUDA/Metal model. Within
 * every loop over gpu block indices, fuse the inner loops over thread
 * indices into a single loop (with predication to turn off
 * threads). Push if conditions between GPU blocks to the innermost GPU threads.
 * Also injects synchronization points as needed, and hoists
 * shared allocations at the block level out into a single shared
 * memory array, and heap allocations into a slice of a global pool
 * allocated outside the kernel. */
Stmt fuse_gpu_thread_loops(Stmt s, const Target &t,
                           const std::map<std::string, Function> &env);

}  // namespace Internal
}  // namespace Halide

#endif
